;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;; This is my own (c) string:;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Copyright  MACRO 
Cprght	     db 10,13,'Written by Olli <olli@digger.org.ru>.',10,13,'$'
             db 'License is GNU GPL',10,13
	     db 'Author does not carry any responsibility for any loss of data',10,13
	     db ' via  use of this programm.',10,13
	     db ' License is GPLv2.',10,13,'$'
           ENDM
